services:
  backend:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://my_user:a-very-strong-password@db:5432/my_courses_db
      - SECRET_KEY=${SECRET_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - APP_ENV=development
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=a-very-strong-password
      - POSTGRES_DB=my_courses_db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
