"""Add username column to user table

Revision ID: 7433b5f7cca0
Revises: 8c0ab9bde3ae
Create Date: 2025-07-03 17:33:47.850564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7433b5f7cca0'
down_revision: Union[str, Sequence[str], None] = '8c0ab9bde3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
