"""Add notification in user table

Revision ID: 8c0ab9bde3ae
Revises: 77fa45c72ed0
Create Date: 2025-06-29 19:52:30.456119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c0ab9bde3ae'
down_revision: Union[str, Sequence[str], None] = '77fa45c72ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


user_notifications_enum_pg = postgresql.ENUM('YES', 'NO', name='usernotifications')

def upgrade() -> None:
    """Upgrade schema."""
    user_notifications_enum_pg.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('notifications', user_notifications_enum_pg, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'notifications')
    user_notifications_enum_pg.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
