services:
  telegram-bot:
    build: .
    container_name: daha-telegram-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - USER_DATA_API_ENDPOINT=${USER_DATA_API_ENDPOINT}
      - API_TOKEN=${API_TOKEN}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
      - BASE_URL=${BASE_URL}
    volumes:
      - ./logs:/logs
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"] 
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/goga1/daha/telegram-bot/nginx.conf:/etc/nginx/conf.d/default.conf 
      - /home/goga1/daha/telegram-bot/certificate.crt:/etc/ssl/certs/certificate.crt
      - /home/goga1/daha/telegram-bot/private.key:/etc/ssl/private/private.key
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - telegram-bot
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  exports:
  logs:
